### ISSUE TITLE
Spawner failed to start [status=1]

### ISSUE THREAD

**Issue by justinnaldzin** [GoogleCloudPlatform/gke-jupyter-classroom#8]
This repo no longer works.  Following the tutorial on [https://cloud.google.com/solutions/using-tensorflow-jupyterhub-classrooms](https://cloud.google.com/solutions/using-tensorflow-jupyterhub-classrooms)

`FROM b.gcr.io/tensorflow/tensorflow:latest` has been deprecated but used in [this Dockerfile](https://github.com/GoogleCloudPlatform/gke-jupyter-classroom/blob/master/jupyter/tf-deepdream/Dockerfile#L21)

Also as mentioned in issue #6 [build fails in these lines](https://github.com/GoogleCloudPlatform/gke-jupyter-classroom/blob/master/jupyter/gcp-tools/Dockerfile#L40-L46) because the Python2 environment isn't found. Probably removed from the latest docker build of "jupyter/scipy-notebook"

Even fixing the above issues results in a "Spawner failed to start [status=1]"

![screen shot 2018-04-13 at 10 47 28 am](https://user-images.githubusercontent.com/12646414/38742446-8c9c8ae6-3f0a-11e8-9e79-693b51f37192.png)

```tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=1])
raise web.HTTPError(500, "Spawner failed to start [status=%s]" % status)
File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 333, in spawn_single_user
yield self.spawn_single_user(user, options=options)
File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/pages.py", line 105, in post
Traceback (most recent call last):
[E 2018-04-13 14:43:38.679 JupyterHub pages:107] Failed to spawn single-user server with form
[I 2018-04-13 14:43:38.600 JupyterHub spawner:508] got Pod URL https://10.59.240.1:443/api/v1/namespaces/jupyterhub/pods
[D 2018-04-13 14:43:28.618 JupyterHub spawner:561] Kubernetespawner get_state: {}
[D 2018-04-13 14:43:28.618 JupyterHub spawner:316] Polling subprocess every 30s
[E 2018-04-13 14:43:28.617 JupyterHub spawner:592] Error starting container response: <Response [403]>
[I 2018-04-13 14:43:28.595 JupyterHub spawner:508] got Pod URL https://10.59.240.1:443/api/v1/namespaces/jupyterhub/pods
[D 2018-04-13 14:43:28.522 JupyterHub spawner:587] Starting Kubernetespawner {'apiVersion': 'v1', 'kind': 'Pod', 'spec': {'containers': [{'volumeMounts': [{'name': 'justin-domain-com-nfs', 'mountPath': '/mnt/notebooks'}, {'name': 'no-api-access', 'mountPath': '/var/run/secrets/kubernetes.io/serviceaccount', 'readOnly': True}], 'name': 'jupyter', 'resources': {'requests': {'cpu': '200m', 'memory': '256Mi'}, 'limits': {'cpu': '3000m', 'memory': '2Gi'}}, 'image': 'gcr.io/cloud-solutions-images/tf-deepdream-su:latest', 'env': [{'name': 'JPY_HUB_PREFIX', 'value': '/hub/'}, {'name': 'JPY_API_TOKEN', 'value': '36b6c10f103f4c949f164f800ddd8489'}, {'name': 'JPY_HUB_API_URL', 'value': 'http://jupyterhub-api.jupyterhub.svc.cluster.local:8081/hub/api'}, {'name': 'JPY_COOKIE_NAME', 'value': 'jupyter-hub-token-justin%domain.com'}, {'name': 'NOTEBOOK_DIR', 'value': '/mnt/notebooks'}, {'name': 'JPY_BASE_URL', 'value': '/user/justin@domain.com'}, {'name': 'YOURNAME', 'value': 'justin@domain.com'}, {'name': 'JPY_USER', 'value': 'justin@domain.com'}]}], 'volumes': [{'nfs': {'path': '/data/notebooks/justin-domain-com', 'server': '10.142.0.3'}, 'name': 'justin-domain-com-nfs'}, {'name': 'no-api-access', 'emptyDir': {}}]}, 'metadata': {'name': 'jupyter-justin-domain-com', 'labels': {'name': 'jupyter-justin-domain-com'}}}```

**Comment by ghost** [comment]
@justinnaldzin : Have you found any solution for that, I am getting the same error and don't know what to do.

**Comment by ernestojeda** [comment]
I was able to get around this by running this command to give the Kubernetes "default" service account cluster admin access to the "jupyterhub" namespace.

`kubectl create clusterrolebinding jupyterhubClusterRoleBinding --clusterrole=cluster-admin --serviceaccount=jupyterhub:default`

This is a temporary solution and I did this just to try and finish the tutorial.
